showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
fontFamily: 等距更纱黑体 Slab SC
editor: 1
mixinText: |
  # author: Waoap
  # version: 22.12.9
  # update: 2022/12/9
  mixin: # Mixin 配置文件
    dns:
      enable: true
      ipv6: true
      # 从 v0.18.8 版本开始，TUN 模式建议使用 fake-ip 模式，redir-host 将无法进行远端 DNS 解析
      enhanced-mode: fake-ip # redir-host/fake-ip
      fake-ip-filter:
        # === Local ===
        - '*.lan'
        - '*.local'

        # === Microsoft Windows Serivice ===
        - '*.msftncsi.com'
        - '*.msftconnecttest.com'

        # === NTP Service ===
        - time.*.com
        - time.*.gov
        - time.*.edu.cn
        - '*.time.edu.cn'
        - time1.*.com
        - time2.*.com
        - time3.*.com
        - time4.*.com
        - time5.*.com
        - time6.*.com
        - time7.*.com
        - ntp.*.com
        - ntp1.*.com
        - ntp2.*.com
        - ntp3.*.com
        - ntp4.*.com
        - ntp5.*.com
        - ntp6.*.com
        - ntp7.*.com
        - ntp.*.*.cn
        - '*.ntp.org.cn'
        - '*.pool.ntp.org'

        # === Music Service ===
        ## NetEase
        - '*.music.163.com'
        - '*.126.net'
        ## Baidu
        - musicapi.taihe.com
        - music.taihe.com
        ## Kugou
        - songsearch.kugou.com
        - trackercdn.kugou.com
        ## Kuwo
        - '*.kuwo.cn'
        ## JOOX
        - api-jooxtt.sanook.com
        - api.joox.com
        - joox.com
        ## QQ
        - '*.y.qq.com'
        - '*.music.tc.qq.com'
        - aqqmusic.tc.qq.com
        - '*.stream.qqmusic.qq.com'

        # === Game Service ===
        ## Nintendo Switch
        - '*.n.n.srv.nintendo.net'
        ## Sony PlayStation
        - '*.stun.playstation.net'
        ## Microsoft Xbox
        - xbox.*.*.microsoft.com
        - '*.*.xboxlive.com'

        # === Others ===
        - wlsy.cqut.edu.cn
        ## QQ Quick Login
        - localhost.ptlogin2.qq.com
        ## Golang
        - proxy.golang.org
        ## STUN Server
        - +.stun.*.*
        - +.stun.*.*.*
        - +.stun.*.*.*.*
        - +.stun.*.*.*.*.*
        ## WORKGROUP
        - WORKGROUP
      default-nameserver:
        - 223.5.5.5 # 阿里DNS
        - 119.29.29.29 # 腾讯DNS
        - 1.1.1.1 # Cloudflare DNS
        - 1.0.0.1 # Cloudflare DNS
      nameserver: # GeoIP 为 CN 时使用的 DNS NameServer
        - 223.5.5.5 # 阿里DNS
        - 180.76.76.76 # 百度DNS
        - 119.29.29.29 # 腾讯DNS
        - 114.114.114.114 # 114DNS
      fallback: # GeoIP 不是 CN 时使用的 DNS NameServer
        - 'https://dns.google/dns-query'
        - 'https://1.1.1.1/dns-query'
        - 'https://1.0.0.1/dns-query'
        - 'https://doh.dns.sb/dns-query'
      fallback-filter:
        geoip: true # 启用 GeoIP
        geoip-code: CN
        ip-cidr:
          - 240.0.0.0/4
        domain:
          - '+.google.com'
          - '+.facebook.com'
          - '+.twitter.com'
          - '+.youtube.com'
          - '+.xn--ngstr-lra8j.com'
          - '+.google.cn'
          - '+.googleapis.cn'
          - '+.googleapis.com'
          - '+.gvt1.com'
    tun: # Tun 配置
      enable: true
      stack: system # 使用 system stack 需要在防火墙放行程序
      dns-hijack:
        - any:53
      auto-route: true
      auto-detect-interface: true
profileParsersText: >
  # author: Waoap

  # version: 22.12.9

  # update: 2022/12/9

  parsers: # array
    # - reg: ^.*$ 匹配所有订阅，或  - url: https://example.com/profile.yaml 指定订阅
    - reg: ^.*$
      # 删除服务商提供的策略组、规则提供者和规则
      code: |
        module.exports.parse = (raw, { yaml }) => {
          const rawObj = yaml.parse(raw)
          const dns = {}
          const proxyGroups = []
          const ruleProviders = []
          const rules = []
          return yaml.stringify({ ...rawObj, dns,'proxy-groups': proxyGroups, 'rule-providers': ruleProviders, rules })
        }
      # 建立自己的配置
      yaml:
        # 策略组示例
        # - name: 分组名
        #   type: select       # 手动选点
        #   url-test           # 自动选择延迟最低的节点
        #   fallback           # 节点故障时自动切换下一个
        #   laod-balance       # 均衡使用分组内的节点
        #   url: http://www.gstatic.com/generate_204       # 测试地址 非select类型分组必要
        #   interval: 300      # 自动测试间隔时间，单位秒 非select类型分组必要
        #   tolerance: 50      # 允许的偏差，节点之间延迟差小于该值不切换 非必要
        #   proxies:
        #       - 节点名称或其他分组套娃
        prepend-proxy-groups: # 建立策略组
          - name: 🔯 MAGIC
            type: url-test
            url: http://www.gstatic.com/generate_204
            interval: 86400
            proxies:
              - DIRECT

          - name: 🔰 选择节点
            type: select

          - name: ✈️ 自动选择
            type: url-test
            url: http://www.gstatic.com/generate_204
            interval: 300
            tolerance: 50

          - name: PROXY
            type: url-test
            url: http://www.gstatic.com/generate_204
            interval: 86400
            proxies:
              - 🔰 选择节点

        commands:
          - proxy-groups.🔰 选择节点.proxies+[]proxyNames # 向指定策略组添加订阅中的节点名，可使用正则过滤
          - proxy-groups.🔰 选择节点.proxies.0+DIRECT # 向指定分组第一个位置添加一个 DIRECT 节点名
          - proxy-groups.🔰 选择节点.proxies.1+✈️ 自动选择 # 向指定分组第二个位置添加一个 自动选择 节点名
          - proxy-groups.✈️ 自动选择.proxies+[]proxyNames
          # 一些可能用到的正则过滤节点示例，使分组更细致
          # []proxyNames|a                         # 包含a
          # []proxyNames|^(.*)(a|b)+(.*)$          # 包含a或b
          # []proxyNames|^(?=.*a)(?=.*b).*$        # 包含a和b
          # []proxyNames|^((?!b).)*a((?!b).)*$     # 包含a且不包含b
          # []proxyNames|^((?!b|c).)*a((?!b|c).)*$ # 包含a且不包含b或c
        # 添加规则
        prepend-rules: # 规则由上往下遍历，如上面规则已经命中，则不再往下处理
          # 自定义规则，在这里添加自己的新规则
          - DOMAIN,www.msftconnecttest.com,PROXY

          # provider 的匹配规则
          - RULE-SET,lancidr,DIRECT,no-resolve
          - RULE-SET,cncidr,DIRECT,no-resolve

          - RULE-SET,reject,REJECT

          - RULE-SET,icloud,DIRECT
          - RULE-SET,apple,DIRECT
          - RULE-SET,google,PROXY

          - RULE-SET,gfw,PROXY
          - RULE-SET,greatfire,PROXY
          - RULE-SET,tld-not-cn,PROXY

          - RULE-SET,telegramcidr,PROXY,no-resolve

          - RULE-SET,proxy,PROXY
          - RULE-SET,direct,DIRECT
          - GEOIP,CN,DIRECT
          - MATCH,🔯 MAGIC
        # 混合规则集
        mix-rule-providers:
          reject:
            type: http
            behavior: domain
            url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt'
            path: ./ruleset/reject.yaml
            interval: 86400

          icloud:
            type: http
            behavior: domain
            url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt'
            path: ./ruleset/icloud.yaml
            interval: 86400

          apple:
            type: http
            behavior: domain
            url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt'
            path: ./ruleset/apple.yaml
            interval: 86400

          google:
            type: http
            behavior: domain
            url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt'
            path: ./ruleset/google.yaml
            interval: 86400

          proxy:
            type: http
            behavior: domain
            url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt'
            path: ./ruleset/proxy.yaml
            interval: 86400

          direct:
            type: http
            behavior: domain
            url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt'
            path: ./ruleset/direct.yaml
            interval: 86400

          gfw:
            type: http
            behavior: domain
            url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt'
            path: ./ruleset/gfw.yaml
            interval: 86400

          greatfire:
            type: http
            behavior: domain
            url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt'
            path: ./ruleset/greatfire.yaml
            interval: 86400

          tld-not-cn:
            type: http
            behavior: domain
            url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt'
            path: ./ruleset/tld-not-cn.yaml
            interval: 86400

          telegramcidr:
            type: http
            behavior: ipcidr
            url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt'
            path: ./ruleset/telegramcidr.yaml
            interval: 86400

          cncidr:
            type: http
            behavior: ipcidr
            url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt'
            path: ./ruleset/cncidr.yaml
            interval: 86400

          lancidr:
            type: http
            behavior: ipcidr
            url: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt'
            path: ./ruleset/lancidr.yaml
            interval: 86400
hideUnselectableGroup: true
systemTheme: true
bypassText: |
  bypass:
      - localhost
      - 127.*
      - 10.*
      - 172.16.*
      - 172.17.*
      - 172.18.*
      - 172.19.*
      - 172.20.*
      - 172.21.*
      - 172.22.*
      - 172.23.*
      - 172.24.*
      - 172.25.*
      - 172.26.*
      - 172.27.*
      - 172.28.*
      - 172.29.*
      - 172.30.*
      - 172.31.*
      - 192.168.*
      - <local>
connProxy: 1
connProfile: true
connMode: true
connChainType: 2
randomMixedPort: false
